### ISSUE TITLE
require error

### ISSUE THREAD

**Issue by lowieliang** [PeelTechnologies/react-native-tcp#32] opened 2017-01-10 11:36 UTC
var net = require('react-native-tcp') report error "Object prototype only be an Object or null"
debug into node_modules\readable-stream\lib\_stream_readable.js : 54
    util.inherits(Readable, Stream);
because require("stream") return object.prototype is 'undifined'
so, util.inherits failure

My ReactNative version is 0.39.2  and react-native-tcp is 3.0.6(latest version)

**Comment by aprock** [comment] 2017-01-10 20:36
which version of rn-nodeify are you using?

**Comment by lowieliang** [comment] 2017-01-11 03:46
hi, my rn-nodeify is latest, vesion 7.0.1
I followed the way that in the code page, "npm install --save-dev rn-nodeify"
Is it right?

**Comment by lowieliang** [comment] 2017-01-11 04:22
Should I install earlier version?

**Comment by lowieliang** [comment] 2017-01-11 10:37
Oop, install rn-nodeify@6.0.1, but has problem too. "Unable to resolve module stream from D:\ReactSamples\Native\Test3\node_modules\readable-stream\readable.js: Module does not exist in the module map or in these directories"
ps: I have tried "react-native start --reset-cache"

**Comment by aprock** [comment] 2017-01-11 16:56
you need to install stream via rn-nodeify

rn-nodeify --install stream,process,util --hack

**Comment by lowieliang** [comment] 2017-01-12 01:51
install stream,process,util  under which rn-nodeify versin?  7.0.1 or 6.0.1 ?

**Comment by lowieliang** [comment] 2017-01-12 03:19
Sorry, I forgot that report the process.
a. I init a new project "Test3"
b. "npm install --save react-native-tcp" & "react-native link react-native-tcp"
c.  "npm install --save-dev rn-nodeify@6.0.1"   to install a lower version
d. "rn-nodeify --install stream,process,util --hack"
e. run project "Test3" in simulator

So, report "Unable to resolve module stream from D:\ReactSamples\Native\Test3\node_modules\readable-stream\readable.js: Module does not exist in the module map or in these directories"

**Comment by lowieliang** [comment] 2017-01-12 03:22
In this morning I try hack again "rn-nodeify --install stream,process,util --hack"
but, it refuse to reinstall:

D:\ReactSamples\Native\Test3>node_modules\.bin\rn-nodeify --install stream,proce
ss,util --hack
not reinstalling stream-browserify
not reinstalling process
not reinstalling util
not reinstalling readable-stream

**Comment by lowieliang** [comment] 2017-01-12 03:25
I install rn-nodeify versin 7.0.1 in another project "Test2", the error occured that I  described in my comment 2 days ago.

**Comment by aprock** [comment] 2017-01-12 17:46
1. what version of react-native? 0.40 has some breaking changes in it.
2. does the example code work for you?
3. what is the output from "rn-nodeify --install stream,process,util --hack"? you may have to run the command manually "./node_modules/rn-nodeify/cmd.js --install stream,process,util --hack"

**Comment by lowieliang** [comment] 2017-01-13 01:34
I use react-native 0.39.2, but my colleague upgraged to version 0.4.0. And he has the same problem too.
OKay. I'll try manually "./node_modules/rn-nodeify/cmd.js --install stream,process,util --hack" today. THX.

**Comment by aprock** [comment] 2017-01-17 16:59
any updates on this? have you been able to test the sample project?

**Comment by aprock** [comment] 2017-01-19 19:37
closing since this can't be reproduced

**Closed by aprock** 2017-01-19 19:37 UTC

**Comment by faxioman** [comment] 2017-08-26 07:50
+1 with:
React native 0.47.0
Node 6.11.2
Android Emulator

Newly created app with create-react-native-app and a simple
```
import 'net'
```

**Comment by faxioman** [comment] 2017-08-26 07:56
Solved after relaunching: 
```
rn-nodeify --install stream,process,util --hack
```

Probably a previously added npm package broke something in node_modules

**Comment by guiac** [comment] 2018-09-04 03:05
@faxioman, I have the same problem. I installed the package (npm install --save-dev rn-nodeify) and then used the following command: rn-nodeify --install stream, process, util - hack. But this returned me that this is an invalid command. Can you help me?
